export const cvData = {
  personal: {
    name: "Juan Alís",
    title: "Technical Support Specialist | IT & Automation",
    location: "Barcelona, Spain",
    email: "juanaliswork@gmail.com",
    phone: "+34 666 771 135",
    linkedin: "https://www.linkedin.com/in/juan-al%C3%ADs-1309aa345/",
    project: "https://swiss-transit-dashboard-real-time-r.vercel.app/",
  },

  experience: {
    sectors: [
      {
        key: "saas",
        label: "IT Support — B2B SaaS",
        description: "iGaming · AI-enabled HR · Cloud infrastructure",
        color: "indigo",
        jobs: [
          {
            company: "PlaylogiQ",
            role: "IT Support Specialist (L3)",
            period: "Jan 2026 – Present",
            location: "Barcelona · Hybrid",
            achievements: [
              "Own end-to-end L3 technical support across payments, KYC, access management, and transaction-status workflows in a B2B iGaming SaaS environment.",
              "Perform structured RCA through log analysis, JSON inspection, and browser debugging with Chrome DevTools; validate API integrations and webhooks in Postman before escalation.",
              "Troubleshoot IAM/access issues (roles, permissions, account recovery) and manage user accounts in Active Directory.",
              "Designed and rolled out a new Zendesk triage/escalation workflow — custom fields, tags, macros, routing rules — to standardise ticket quality and reduce unnecessary Engineering escalations.",
              "Built an automated workflow using a multi-port GSM/4G LTE gateway and secure VPN to convert bank confirmation SMS into JSON and forward via HTTPS API for real-time transaction processing.",
              "Developed an automated workflow for company email signatures using Google Workspace API and Node.js, generating HTML signatures from CSV user data.",
            ],
            kpis: [
              "↓56% tickets escalated to Engineering",
              "↓18% escalations to L3",
              "Real-time SMS payment processing",
            ],
          },
          {
            company: "PlaylogiQ",
            role: "IT Customer Support Specialist",
            period: "Apr 2025 – Jan 2026",
            location: "Barcelona · Hybrid",
            achievements: [
              "Provided multilingual B2B support (Spanish, French, English) via chat and email — onboarding, account access, KYC, deposits/withdrawals, and transaction issues.",
              "Managed ticketing in Zendesk with structured triage, prioritisation, and clean escalation handoffs to Level 2 and Level 3.",
              "Built an automated Player Report workflow (Report Chatbot) using n8n + Telegram, eliminating repetitive manual report export requests.",
              "Built an automated workflow to review Zendesk tickets using n8n and ChatGPT via OpenAI API — sentiment analysis, quality scoring, and suggested agent replies.",
            ],
            kpis: [
              "↓89% report-request tickets",
              "Faster KPI calculation",
              "Multilingual: ES / FR / EN",
            ],
          },
          {
            company: "LeanTech",
            role: "IT Customer Support Specialist",
            period: "2024 – Apr 2025",
            location: "Remote",
            achievements: [
              "Managed tickets in Zendesk, applying structured triage, prioritisation, and clean escalations to L2/L3 through Zendesk and Jira, ensuring full case follow-up.",
              "Audited AI agent conversations to identify quality gaps — intent mismatches, missing context, unclear responses — and proposed improvements.",
              "Identified recurring issues and converted them into documentation, FAQs, and SOPs to reduce repeated user questions.",
              "Collaborated closely with Product and Engineering teams to escalate complex issues, document bugs with solid evidence, and follow through until fixes were implemented.",
            ],
            kpis: [],
          },
        ],
      },
      {
        key: "infra",
        label: "Electrical Infrastructure & Telecom",
        description: "Fiber optics · GSM networks · Electrical systems",
        color: "cyan",
        jobs: [
          {
            company: "Alp'com",
            role: "Telecommunications Technician",
            period: "2022 – 2023",
            location: "Auvergne-Rhône-Alpes, France",
            achievements: [
              "Deployed fiber optic infrastructure in industrial and remote areas.",
              "Performed fusion splicing, OTDR testing, and fiber termination to ensure high-speed connectivity.",
              "Installed GSM network equipment, aligned RF antennas, and configured transmission systems on telecom towers to optimise mobile signal coverage.",
              "Installed access control and video surveillance systems.",
              "Managed structured cabling (Cat6/Cat6A and Cat7), routers, and switches in data centre racks.",
            ],
            kpis: [],
          },
          {
            company: "Generalitat de Catalunya",
            role: "Electrical Technician",
            period: "2018 – 2020",
            location: "L'Hospitalet de Llobregat, Spain",
            achievements: [
              "Installed and maintained electrical systems in residential, commercial, and industrial environments.",
              "Ensured installations complied with REBT regulations and safety standards.",
              "Read electrical blueprints to route conduits and install wiring.",
              "Assembled electrical panels, circuit breakers, and three-phase power distribution systems.",
              "Diagnosed electrical faults using multimeters, insulation testers, and diagnostic tools.",
            ],
            kpis: [],
          },
        ],
      },
      {
        key: "ops",
        label: "Operations & Team Management",
        description: "Retail · Semi-luxury · Supply chain",
        color: "violet",
        jobs: [
          {
            company: "JOTT",
            role: "B2C Sales Advisor — Semi-Luxury",
            period: "2023 – 2024",
            location: "Spain",
            achievements: [
              "Delivered personalised service in a semi-luxury fashion environment, improving customer experience and loyalty.",
              "Assisted in product selection and management of special client requests.",
              "Built lasting client relationships, increasing returning customers and positive reviews.",
              "Supported inventory management and after-sales service.",
            ],
            kpis: [],
          },
          {
            company: "Super U",
            role: "Store Deputy Manager",
            period: "2021 – 2022",
            location: "France",
            achievements: [
              "Managed a team of 18 people, optimising workflows and inventory management.",
              "Ensured shelves were stocked and organised to improve the customer experience.",
              "Handled customer queries and complaints, improving satisfaction scores.",
              "Coordinated with supply chain to prevent stock shortages.",
              "Supported training, scheduling, and performance evaluation of team members.",
            ],
            kpis: [],
          },
          {
            company: "Super U",
            role: "Commercial Employee",
            period: "2020 – 2021",
            location: "France",
            achievements: [
              "Maintained merchandising standards and inventory management.",
              "Applied FIFO protocols, reducing waste and stock shortages.",
              "Provided customer assistance and supported promotional campaigns.",
            ],
            kpis: [],
          },
        ],
      },
    ],
  },

  education: [
    {
      degree: "Bachelor's Degree in Computer Systems Engineering",
      institution: "UOC – Universitat Oberta de Catalunya",
      period: "Starting Sep 2026",
      description: "Upcoming enrolment.",
      highlight: null,
      projectUrl: null,
      tags: ["Upcoming"],
    },
    {
      degree: "Backend Development Bootcamp",
      institution: "CIFO – Centres d'Innovació i Formació Ocupacional",
      period: "Jul 2025 – Oct 2025",
      description:
        "Intensive backend programme focused on PHP and Laravel — RESTful API design, MVC architecture, Eloquent ORM, database migrations, and deployment workflows.",
      highlight: null,
      projectUrl: null,
      tags: ["PHP", "Laravel", "Backend"],
    },
    {
      degree: "Database Optimisation with Advanced SQL",
      institution: "IT Academy de Barcelona Activa",
      period: "2024",
      description: "Query optimisation, indexing strategies, and complex joins on production-scale datasets.",
      highlight: null,
      projectUrl: null,
      tags: ["SQL", "Databases"],
    },
    {
      degree: "Frontend Development Bootcamp",
      institution: "IT Academy de Barcelona Activa",
      period: "Sep 2024 – Jun 2025",
      description:
        "Built responsive web applications with React, JavaScript, and TypeScript. Styled with Tailwind CSS and Bootstrap. Deployed projects via Vercel.",
      highlight:
        "Capstone: Real-time SBB Dashboard — live departure/arrival boards, connection routing, and searchable directory across 500+ Swiss transit stations.",
      projectUrl: "https://swiss-transit-dashboard-real-time-r.vercel.app/",
      tags: ["React", "TypeScript", "Tailwind"],
    },
    {
      degree: "Higher Technician — Industrial Automation & Robotics",
      institution: "Instituto Llobregat",
      period: "Sep 2023 – Jun 2025",
      description:
        "Electrical, pneumatic, and hydraulic systems; PLC programming (TIA Portal, Ladder, SCL, Grafcet); industrial robotics and electromechanical systems.",
      highlight: null,
      projectUrl: null,
      tags: ["PLCs", "Robotics", "TIA Portal"],
    },
    {
      degree: "Technical Diploma in Electrical & Automated Systems",
      institution: "Instituto Llobregat",
      period: "Sep 2017 – Jun 2019",
      description:
        "REBT regulations, industrial automation, electrotechnics, home automation, solar PV installations, and ICT infrastructure in buildings.",
      highlight: null,
      projectUrl: null,
      tags: ["REBT", "Automation", "Electrical"],
    },
  ],

  certifications: [
    { name: "Google IT Support Professional Certificate", issuer: "Google" },
    { name: "AWS Cloud Fundamentals: Core Services & Architecture", issuer: "AWS" },
    { name: "ELEE0109 Certification", issuer: "Gornal Activa" },
  ],

  skills: {
    categories: [
      {
        key: "support",
        label: "Support & Incident Management",
        color: "indigo",
        items: [
          "Technical Support",
          "Incident Management",
          "Root Cause Analysis",
          "SLA Management",
          "Escalation Management",
          "Triage",
          "ITIL / ITSM",
          "Zendesk",
          "Jira",
          "Active Directory",
          "IAM / Access Control",
        ],
      },
      {
        key: "tools",
        label: "Technical Tools",
        color: "cyan",
        items: [
          "Postman",
          "Chrome DevTools",
          "SQL",
          "AWS",
          "MongoDB",
          "AWS CloudWatch",
          "Google Workspace",
          "Microsoft Teams",
          "Slack",
        ],
      },
      {
        key: "apis",
        label: "Integration & APIs",
        color: "violet",
        items: [
          "REST API",
          "Webhook Validation",
          "JSON / XML Inspection",
          "Log Analysis",
          "API Debugging",
          "Postman Collections",
          "OAuth 2.0",
          "HTTPS / TLS",
        ],
      },
      {
        key: "automation",
        label: "Automation & AI",
        color: "emerald",
        items: [
          "n8n",
          "OpenAI API",
          "AI Agents",
          "Workflow Automation",
          "AI Conversation Auditing",
          "SMS-to-API Pipelines",
          "Telegram Bots",
          "ChatGPT",
        ],
      },
      {
        key: "dev",
        label: "Development",
        color: "amber",
        items: [
          "JavaScript",
          "TypeScript",
          "Node.js",
          "React",
          "PHP",
          "Laravel",
          "HTML / CSS",
          "Tailwind CSS",
          "Bootstrap",
          "Styled Components",
          "Git / GitHub",
          "Firebase",
          "Vercel",
          "Webpack",
          "Vite",
        ],
      },
      {
        key: "industrial",
        label: "Industrial & Automation",
        color: "rose",
        items: [
          "TIA Portal",
          "KOP / Ladder",
          "SCL",
          "Grafcet",
          "AutoCAD",
          "EPLAN",
          "PLCs",
          "Industrial Robotics",
          "REBT",
          "EcoStruxure Machine Expert",
          "Unity Pro",
          "ROBOGUIDE",
        ],
      },
    ],
    languages: [
      { flag: "🇪🇸", lang: "Spanish", level: "Native" },
      { flag: "🇪🇸", lang: "Catalan", level: "Native" },
      { flag: "🇫🇷", lang: "French", level: "C1" },
      { flag: "🇬🇧", lang: "English", level: "B2" },
      { flag: "🇮🇹", lang: "Italian", level: "A2" },
    ],
  },
};
